apiVersion: apps/v1
kind: Deployment
metadata:
  name: tickets-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tickets
  template:
    metadata:
      labels:
        app: tickets
    spec:
      containers:
        - name: tickets
          image: us.gcr.io/react-micro-308901/tickets
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-secret
                  key: JWT_KEY_SECRET
            - name: TICKETS_MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: tickets_mongo_url
            - name: NATS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-configmap
                  key: nats-service-url
            - name: NATS_TICKET_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-configmap
                  key: nats-ticket-cluster-id
            - name: NATS_TICKET_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # pod id
---
apiVersion: v1
kind: Service
metadata:
  name: tickets-service
spec:
  selector:
    app: tickets
  ports:
    - name: tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
